### ISSUE TITLE
Remove the timeout

### ISSUE THREAD

**Issue by Melab** [timvisee/apbf#1]
Is it possible to remove the timeout enforcement from TWRP? Also, are you aware that people have been having trouble with TWRP decryption in that it wouldn't decrypt even after it's given the right password?

**Comment by timvisee** [comment]
@Melab I don't think it's possible to disable the cooldown delay, without compiling TWRP yourself.

Yes, I'm aware of decryption failures, but I didn't note this in the README.

**Comment by timvisee** [comment]
I'll close this for now, as I don't think this is noting any issue in `apbf` itself.

Note that you can disable the timeout used by `apbf` by setting [`ATTEMPT_TIMEOUT`](https://github.com/timvisee/apbf/blob/f7eb071b9c298ec279cac65072cc21e190e61b1a/src/config.rs#L76) to zero in the `config.rs` file. This is not what you requested, but I wanted to state it anyway.

Please open it again if you have any other questions. :wink:
