### ISSUE TITLE
TWRP without timeout

### ISSUE THREAD

**Issue by witchent** [timvisee/apbf#4]
Do you have a pointer on where I can find the source code for the timeout of TWRP?
As I sadly have set a 4x4 pattern, it is not feasible to brute force it with 10 seconds timeout, so instead I would like to give it one last try and compile TWRP without this timeout, so I can bruteforce it more quickly. But sadly I cannot find the corresponding source code line.
Thank you very much for your tool by the way.

**Comment by timvisee** [comment]
> Do you have a pointer on where I can find the source code for the timeout of TWRP?

I don't. When looking into this way back I couldn't find there this was actually enforced.

If you do come come across it, please feel free to share about it here.

**Comment by 3060PlayZ-github** [comment]
Maybe because the chips inside the phone enforce it themselves?
